export const LINES = [
  "Finishing",
  "Melting",
  "Core Making",
  "RCS",
  "Moulding-Sand",
  "Die Press",
];

export const SOURCES = ["BM", "PM", "IMP"];

export const FINISHING_MACHINES = [
  "HSB 006",
  "HSB 005",
  "M/C Auto Grinding",
  "Junbiki",
  "Spray Booth",
  "Others",
];

export const MACHINES_BY_LINE = {
  Finishing: [
    { no: "ISBI-001", name: "SPRAY BOOTH" },
    { no: "IDC-003", name: "DUST COLL. FINISHING I & II" },
    { no: "IFHU-005", name: "METALLICONE" },
    { no: "IHOU-015", name: "HOIST KNOCK OUT" },
    { no: "IHOU-019", name: "HOIST METALLICONE" },
    { no: "IHOU-020", name: "HOIST FINAL CHECK 1" },
    { no: "IHOU-023", name: "HOIST ENGINEERING" },
    { no: "IHOU-059", name: "HOIST SPRAY BOOTH" },
    { no: "IHOU-044", name: "HOIST BARITORY" },
    { no: "IHOU-46", name: "HOIST SWING GRINDING" },
    { no: "ISG-001", name: "SWING GRINDER 1" },
    { no: "IKO-001", name: "KNOCK OUT" },
    { no: "IHU-001", name: "HANTEN MACHINE" },
    { no: "HSB-006", name: "HANGER SHOT BLAST 3" },
    { no: "HSB-005", name: "HANGER SHOT BLAST 2" },
    { no: "IHOU-062", name: "HOIST HANGER BLAST 006" },
    { no: "IRCU-003", name: "ROLLER CONVEYOR FINISHING-1" },
    { no: "IRCU-005", name: "COOLING CONVEYOR LINE-1" },
    { no: "IRCU-006", name: "COOLING CONVEYOR LINE-2" },
    { no: "IRCU-007", name: "COOLING CONVEYOR LINE-3" },
    { no: "IRCU-008", name: "COOLING CONVEYOR LINE-4" },
    { no: "IRCU-009", name: "COOLING CONVEYOR LINE-5" },
    { no: "IHU-002", name: "HUNTEN VISUAL CHECK" },
    { no: "ITB-001", name: "THUMBLAST" },
    { no: "IGU-006", name: "NEW GRINDING" },
    { no: "MIJ-001", name: "JUNBIKI" },
  ],

  Melting: [
    { no: "IFHU-003", name: "PREHEATING LADLE 1" },
    { no: "IFHU-004", name: "PREHEATING LADLE 2" },
    { no: "IFHU-009", name: "PREHEATING LADLE 3" },
    { no: "ICSA-001", name: "CARBON SULFUR 1" },
    { no: "ICTO-001", name: "CONSTANT TEMPERATURE OVEN" },
    { no: "IPDA-001", name: "PDA - 7000 1" },
    { no: "ICSA-002", name: "CARBON SULFUR 2" },
    { no: "IGU-005", name: "DOUBLE HEAD GRINDER 5 (ANALYSIS)" },
    { no: "IPDA-002", name: "PDA - 7000 2" },
    { no: "ICPU-001", name: "BALLING M/C" },
    { no: "ICTU -003", name: "COOLING TOWER 3" },
    { no: "ICTU-001", name: "COOLING TOWER 1" },
    { no: "ICTU-002", name: "COOLING TOWER 2" },
    { no: "ICWU-001", name: "COOLING WATER PUMP 1" },
    { no: "ICWU-002", name: "COOLING WATER PUMP 2" },
    { no: "ICWU-003", name: "COOLING WATER PUMP 3" },
    { no: "IEPU-001", name: "ENGINE PUMP NO. 1" },
    { no: "IEPU-002", name: "ENGINE PUMP NO. 2" },
    { no: "IFM-002", name: "FURNACE NO. 1 ( MF .2 New )" },
    { no: "IFM-003", name: "FURNACE NO. 2 ( MF. 3 New )" },
    { no: "IFM-004", name: "FURNACE NO. 3 ( LF. 3 )" },
    { no: "IFM-005", name: "FURNACE NO. 4 ( LF . 4 )" },
    { no: "IHOU-001", name: "CRANE 5 TON NO. 1" },
    { no: "IHOU-002", name: "CRANE 2 TON" },
    { no: "IQRL-001", name: "QRL UNIT 1" },
    { no: "ISPU-004", name: "SUBMERSIBLE PUMP NO. 4 F,CE" },
    { no: "ISPU-001", name: "SUBMERSIBLE PUMP NO. 1 F,CE" },
    { no: "ISPU-002", name: "SUBMERSIBLE PUMP NO. 2 F,CE" },
    { no: "ISPU-003", name: "SUBMERSIBLE PUMP NO. 3 F,CE" },
    { no: "ITH - 001", name: "THERMOCOUPLE HOLDER 1" },
    { no: "IWS-001", name: "WEIGHT SCALE DIGITAL 1" },
    { no: "ITH-002", name: "THERMOCOUPLE HOLDER 2" },
    { no: "ITH-003", name: "THERMOCOUPLE HOLDER 3" },
    { no: "ITH-004", name: "THERMOCOUPLE HOLDER 4" },
    { no: "ITH-005", name: "THERMOCOUPLE HOLDER 5" },
    { no: "ITH-006", name: "THERMOCOUPLE HOLDER 6" },
    { no: "ITH-007", name: "THERMOCOUPLE HOLDER 7" },
    { no: "ITH-008", name: "THERMOCOUPLE HOLDER 8" },
    { no: "IASU-001", name: "AUTO SINTERING 1" },
    { no: "IASU-002", name: "AUTO SINTERING 2" },
    { no: "ITH-010", name: "THERMOCOUPLE HOLDER 10" },
    { no: "ITH-011", name: "THERMOCOUPLE HOLDER 11" },
    { no: "IFM-009", name: "FURNACE NO. 6 ( MF. 1 New )" },
    { no: "IHOU-060", name: "CRANE 5 TON NO. 2" },
    { no: "ISC - 001", name: "SMOKE COLLECTOR" },
    { no: "IWS -005", name: "WEIGHT SCALE DIGITAL 5" },
    { no: "IMC-001", name: "MIXING CONCRETE" },
    { no: "ICTU -005", name: "COOLING TOWER 5 ( Balling )" },
    { no: "ICPU-002", name: "BALLING M/C NEW" },
    { no: "IWS-004", name: "WEIGHT SCALE DIGITAL 4" },
    { no: "IZEU-009", name: "LADDLE NO.9 (SUGIYAMA)" },
  ],

  "Core Making": [
    { no: "ICM-002", name: "SHELL CORE 2 (Fr/Rr)" },
    { no: "ICM-003", name: "SHELL CORE 3 (Wj/Sl)" },
    { no: "IFHU-007", name: "CORE DRYER 1" },
    { no: "IHOU-014", name: "HOIST CORE SAND SUPPLY 1" },
    { no: "IHOU-016", name: "HOIST DOLLY LIFTER" },
    { no: "IHO0-057", name: "HOIST CORE SAND SUPPLY 2" },
    { no: "IHO0-058", name: "HOIST CORE SAND SUPPLY 3" },
    { no: "ICM-006", name: "SHELL CORE MACHINE 6" },
    { no: "ICM-007", name: "SHELL CORE MACHINE 7" },
    { no: "ICM-008", name: "SHELL CORE MACHINE 8" },
    { no: "ICM-009", name: "SHELL CORE MACHINE 9" },
    { no: "IFHU-015", name: "CORE DRIYER 2" },
    { no: "IDU-001", name: "NEW DRILL 1" },
    { no: "IDU-002", name: "NEW DRILL 2" },
    { no: "ICMU-001", name: "COATING MIXER" },
    { no: "IPHU-001", name: "PREHEATING 1" },
    { no: "IPHU-002", name: "PREHEATING 2" },
    { no: "IPHU-003", name: "PREHEATING 3" },
    { no: "IPHU-004", name: "PREHEATING 4" },
    { no: "IEF - 008", name: "SMOKE COLLECTOR" },
    { no: "IRCU 010", name: "ROLLER CONVEYOR CRANK CASE" },
    { no: "ICMU-002", name: "COATING MIXER 2TR" },
    { no: "IPHU-006", name: "PREHEATING 6" },
  ],

  RCS: [
    { no: "IDC-009", name: "DUST COLL. SAND TREATMENT" },
    { no: "IBLU-001", name: "BUCKET LOADER (HOIST)" },
    { no: "IDC-008", name: "DUST COLL. PRE-TREATM RCS" },
    { no: "IFHU-008", name: "FURNACE RCS" },
    { no: "ISX-016", name: "GYRATORY SCREEN" },
    { no: "IFHU-010", name: "SAND HEATER" },
    { no: "IHOU-041", name: "HOIST FURNACE RCS" },
    { no: "IHOU-042", name: "HOIST RECLAIMER 1" },
    { no: "IHOU-043", name: "HOIST RECLAIMER 2" },
    { no: "IHSE -001", name: "HEXAMIN SUPLAY UNIT" },
    { no: "IST-001", name: "STRENGTH TEST" },
    { no: "ISX-009 A", name: "BE - 1 ( 4/10 )" },
    { no: "ISX-009 B", name: "BE - 2 ( 5/10 )" },
    { no: "ISX-009 C", name: "BE - 3 ( 6/10 )" },
    { no: "ISX-009 D", name: "OSCILLATING COOLER RCS" },
    { no: "ISX-010 C", name: "SAND CRUSHER" },
    { no: "ISX-009 E", name: "VIBRATING SCREEN 2" },
    { no: "ISX-009 F", name: "VIBRATING SCREEN 3" },
    { no: "ISX-015", name: "SPEED MULLER RCS" },
    { no: "ISZ -015", name: "SAND RECLAIMER" },
    { no: "IPCU 01", name: "PNEUMATIC CONVEYOR" },
    { no: "IDC-004", name: "DUST COLECTOR FURNACE RCS" },
    { no: "IDC-005", name: "DUST COLECTOR SAND RECLAIMER" },
  ],

  "Moulding-Sand": [
    { no: "IHOU-010", name: "HOIST BENTONIT (SAND SUPPLY)" },
    { no: "IHOU-011", name: "HOIST MIX MULLER" },
    { no: "IHOU-012", name: "AIR HOIST ENDO 1" },
    { no: "IHOU-013", name: "AIR HOIST ENDO 2" },
    { no: "IMC-002", name: "APRON CONVEYOR" },
    { no: "ISX-001", name: "VIBRATING SCREEN 1" },
    { no: "ISX-002", name: "SHAKE OUT" },
    { no: "ISX-003", name: "MAGNET SEPARATOR 1" },
    { no: "ISX-004", name: "ROTARY SCREEN" },
    { no: "ISX-005", name: "SAND COOLER MIA" },
    { no: "ISX-006", name: "BC - 3A ( 3/16 )" },
    { no: "ISX-006", name: "BC - 3B ( 4/16 )" },
    { no: "ISX-006", name: "BC - 11 ( 5/16 )" },
    { no: "ISX-006", name: "BC - 12 ( 6/16 )" },
    { no: "ISX-006", name: "BC - 13 ( 7/16 )" },
    { no: "ISX-006", name: "BC - 14 ( 8/16 )" },
    { no: "ISX-006", name: "BC - 15 ( 9/16 )" },
    { no: "ISX-006", name: "BC - 16 ( 10/16 )" },
    { no: "ISX-006", name: "BC - 17 ( 11/16 ) + WATER SPRAY" },
    { no: "ISX-006", name: "BC - 18 ( 12/16 )" },
    { no: "ISX-006", name: "BC - 19 ( 13/16 )" },
    { no: "ISX-006", name: "BC - 20 ( 14/16 )" },
    { no: "ISX-006", name: "BE - 1 ( 1/10 )" },
    { no: "ISX-006", name: "BE - 11 ( 2/10 ) + NEW VIBRATING" },
    { no: "ISX-006", name: "BE - 12 ( 3/10 )" },
    { no: "ISX-006", name: "BELT FEEDER" },
    { no: "ISX-006", name: "OSCILLATING CONVEYOR 1" },
    { no: "ISX-007", name: "MIX MULLER" },
    { no: "ISX-008", name: "BC - 1 ( 1/16 )" },
    { no: "ISX-008", name: "BC - 2 ( 2/16 )" },
    { no: "ISX-008", name: "COOLER RATOR" },
    { no: "IRCU-001", name: "SAND CONVEYOR" },
    { no: "IRCU-002", name: "RUNNER CONVEYOR" },
    { no: "IRCU-004", name: "TRAVERSER BARASHI" },
    { no: "ISX-006", name: "NEW VIBRATING CONVEYOR" },
    { no: "IDC-015", name: "DUST COLLECTOR BC 15" },
    { no: "IDC-012", name: "DUST COLLECTOR BENTONITE" },
    { no: "IHOU", name: "HOIST ELECTRIC BARASHI" },
    { no: "IRB-001", name: "GATE BREAKER" },
    { no: "IGCG-001", name: "CORE SETTING JIG HANGER 1" },
    { no: "IHOU-003", name: "HOIST POURING A" },
    { no: "IHOU-004", name: "HOIST POURING B" },
    { no: "IHOU-005", name: "HOIST PATTERN CHANGE" },
    { no: "IHOU-006", name: "HOIST CORE SETTING" },
    { no: "IHOU-007", name: "HOIST GAS HOLE DRILL" },
    { no: "IHOU-008", name: "HOIST FLASK PULL OUT" },
    { no: "IHOU-036", name: "HOIST POURING C ( SPARE )" },
    { no: "IMC-001", name: "MOULDING LINE B (GAS DRIL.)" },
    { no: "IMC-001", name: "MOULDING LINE C (F. CLOSING) + AIR BLOW" },
    { no: "IMC-001", name: "MOULDING LINE D (F. FEEDING)" },
    { no: "IMC-001", name: "MOULDING LINE E (F.PULL OUT)" },
    { no: "IMC-001", name: "MOULDING LINE F (F.RELEASING)" },
    { no: "IMO-001", name: "MOULDING MACHINE A (MOULDING)" },
    { no: "IWS-002", name: "WEIGHT SCALE DIGITAL 2" },
    { no: "IWS-003", name: "WEIGHT SCALE DIGITAL 3" },
    { no: "IDC-001", name: "DUST COLLECTOR.SAND PREPARATION" },
    { no: "IDC-002", name: "DUST COLLECTOR.RCS - RCT" },
    { no: "IFHU-006", name: "EXHAUST POURING" },
    { no: "IGM-001", name: "GANTRI" },
  ],

  "Die Press": [
    { no: "IDC-010", name: "DUST COLL. SHORTBLAST" },
    { no: "IPC-001", name: "PLASMA CUTTING M/C" },
    { no: "IGU-001", name: "DOUBLE HEAD GRINDER 1" },
    { no: "ISB-004", name: "HANGER SHOT BLAST 2" },
    { no: "IHOU -", name: "CRANE 10 T MITSUBISHI" },
    { no: "IDSU-001", name: "DAISHA" },
    { no: "IBM-001", name: "BABY MULLER" },
    { no: "IDC-009", name: "DUST COLL. SAND TREATMENT" },
    { no: "IRP-001", name: "RESIN PUMP No.1" },
    { no: "ISHT-001", name: "SAND HARDNESS TESTER" },
    { no: "ISX-010", name: "CONTINUOUS MIXER (WMS-20)" },
    { no: "ISX-011", name: "BE - 05 ( 7/10 )" },
    { no: "ISX-011", name: "BE - 09 ( 8/10 )" },
    { no: "ISX-011", name: "BE - 14 ( 9/10 )" },
    { no: "ISX-011", name: "BE - 16 ( 10/10 )" },
    { no: "ISX-011", name: "MAGNET SEPARATOR 2" },
    { no: "ISX-011", name: "OSCILLATING CONVEYOR 2" },
    { no: "ISX-011", name: "PNEUMATIC CONVEYOR" },
    { no: "ISX-011", name: "SAND COOLER VSA-005" },
    { no: "ISX-011", name: "SAND COOLER WSC-005" },
    { no: "ISX-011", name: "SAND CRUSHER" },
    { no: "ISX-011", name: "SAND RECLAIMER" },
    { no: "ISX-011", name: "VIBRATING SCREEN 4" },
    { no: "IFM-007", name: "FURNACE DIE PRESS" },
    { no: "IASU-003", name: "AUTO SINTERING D/P" },
    { no: "ICTU-004", name: "COOLING TOWER 4" },
    { no: "IFHU-011", name: "DRYING OVEN D/P" },
    { no: "IHOU-051", name: "CRANE 20 T & 40 T" },
    { no: "IQRL-002", name: "QRL UNIT 2" },
    { no: "IZEU-010", name: "LADDLE NO.10 (NGK)" },
    { no: "IZEU-011", name: "LADDLE NO.11 (NGK)" },
    { no: "IZEU-012", name: "LADDLE NO.12 D/P (SUGIYAMA)" },
    { no: "IZEU-013", name: "LADDLE NO.13 (NGK)" },
    { no: "IZEU-014", name: "LADDLE NO.14 (NGK)" },
    { no: "IZEU-015", name: "LADDLE NO.15 (NGK)" },
    { no: "IZEU-016", name: "LADDLE NO.16 (NGK)" },
    { no: "IZEU-017", name: "LADDLE NO.17 (NGK)" },
    { no: "IZEU-018", name: "LADDLE NO.18 (NGK)" },
    { no: "IZEU-019", name: "LADDLE NO.19 (NGK)" },
    { no: "IZEU-020", name: "LADDLE NO.20 (NGK)" },
    { no: "ISC - 002", name: "SMOKE COLLECTOR" },
    { no: "IPHY - 001", name: "POURING HOOD YARD" },
    { no: "IZEU-021", name: "LADDLE NO.21 (NGK)" },
    { no: "IZEU-022", name: "LADDLE NO.22 (NGK)" },
  ],
};

export const LINE_COLORS = {
  "Finishing": "#2563eb",
  "Melting": "#dc2626",
  "Core Making": "#16a34a",
  "RCS": "#9333ea",
  "Moulding-Sand": "#ea580c",
  "Die Press": "#0891b2",
};
